### ISSUE TITLE
FAQ page still shows Android as not being considered for development.

### ISSUE THREAD

**Issue by mascondante** [citra-emu/citra-web#127]
Title explains it. Screenshot for reference. Page in question: https://citra-emu.org/wiki/faq/

![Screenshot_20200310-231455_Chrome](https://user-images.githubusercontent.com/2492044/76379145-b2a02180-6325-11ea-8091-0f0d787b3f27.jpg)

**Comment by FearlessTobi** [comment]
Every user can edit our FAQ wiki pages themselves :)
I fixed this now and the changes will appear on the Website shortly.
