### ISSUE TITLE
Download page has broken macos builds

### ISSUE THREAD

**Issue by Redecorating** [citra-emu/citra-web#168]
The current download page leads macOS users to download versions that don't work as seen here: https://www.reddit.com/r/Citra/comments/z2derk/first_time_installing_citra_on_mac/

From my understanding this is because Citra has temporarily dropped macOS support (this is mentioned in the FAQ page).

To avoid having macOS users downloading versions they are unable to install, i can think of a couple of solutions:

- Could the download page have a note (similar to the note about M1 macs) telling macOS users to look at https://citra-emu.org/wiki/faq/ where there are instructions to get a working version
- could the download links for macOS be changed to only have the older working versions while macOS isn't supported
- or something else that ensures macOS users who go directly to the downloads page won't get confused and be unable to install Citra?

of course when macOS is supported again this would need to be changed back, but currently it's difficult for macOS users to install Citra unless they happen to scroll through the FAQ page.

**Comment by SleepingSnakezzz** [comment]
MacOS is supported again.
