### ISSUE TITLE
Blog RSS feed is gone?

### ISSUE THREAD

**Issue by Parsnip** [citra-emu/citra-web#23]
As per subject, the blog rss feed seems to be gone.

Intentional?

**Comment by chris062689** [comment]
Not intentional. I'll look into it and should have it back up soon!

**Comment by Parsnip** [comment]
Execellent.
I noticed that lately some wiki pages were coming through the rss as well, so I figured that maybe you took it down to fix it or something.

**Comment by chris062689** [comment]
This should now be fixed. I've limited it to only blog posts as well.
Let me know if it's working for you.

Are you using a feed reader or application?
How does it look?

**Comment by Parsnip** [comment]
I'm using Thunderbird and looks like it works great. Thanks for the fast fix too.
