### ISSUE TITLE
Change licensing to AGPL

### ISSUE THREAD

**Issue by chris062689** [citra-emu/citra-web#35]
The current license that citra-web is licensed under is the GPL.
Users do not need to publish their changes due to not distributing it to clients. They are hosting it on a server. 

Not so with the AGPL.

Both versions of the Affero GPL were designed to close a perceived application service provider (ASP) loophole in the ordinary GPL, where, by using but not distributing the software, the copyleftprovisions are not triggered. Each version differs from the version of the GNU GPL on which it is based in having an added provision addressing use of software over a computer network. This provision requires that the full source code be made available to any network user of the AGPL-licensed work, typically a web application.

This hole in the GPL is often called "Application Service Provider" hole.

The GNU Affero General Public License is based on the GNU GPL, but has an additional term to allow users who interact with the licensed software over a network to receive the source for that program. We recommend that people consider using the GNU AGPL for any software which will commonly be run over a network.

Requesting all citra-web contributors vote to change the license of the project to AGPL. 
Open for discussion.

**Comment by chris062689** [comment]
Requesting the following contributors approvals: @Schplee @Saphiresurf @j-selby @bunnei @anodium @BynariStar @TheKoopaKingdom @yuriks @Leo626

**Comment by Schplee** [comment]
I agree with the license change.

**Comment by TheKoopaKingdom** [comment]
That sounds good to me.

**Comment by anodium** [comment]
Sounds perfect :100:

**Comment by bunnei** [comment]
I agree with the license change.

**Comment by Saphiresurf** [comment]
Yep this seems perfect!

**Comment by j-selby** [comment]
Sounds good to me.

**Comment by Leo626** [comment]
The change sounds good to me.

**Comment by BynariStar** [comment]
Sounds good to me :thumbsup:

**Comment by yuriks** [comment]
Have I actually contributed anything to the citra-web repo? If I didn't them you don't need my approval. If I did then I'm not actually 100% sure I can agree with AGPL licensing, I'll have to check.

**Comment by chris062689** [comment]
@yuriks You merged two commits into our repository. 

https://github.com/citra-emu/citra-web/commit/00e61b8d9d7f8a46268787a2c0986509c7ea8267
https://github.com/citra-emu/citra-web/commit/a39c69c235c77ca504b7b49737f910f3d769c2ca

I'm more than happy to hear your feedback before proceeding as you're a core member.

**Comment by yuriks** [comment]
If it's just merges authored by someone else then I hope no copyright over then, you can disregard them as far as licensing goes.

**Comment by chris062689** [comment]
I would still like to hear your concerns over an AGPL license, if you have time to comment.

**Comment by yuriks** [comment]
I don't like viral copyleft licenses in most instances, and the AGPL is even more extreme in that regard, but SGTM. I just don't know if I can contribute to it later (though I don't have much interest in maintaining the web services code to begin with.)
