### ISSUE TITLE
Progress Report 2017 August

### ISSUE THREAD

**Issue by anodium** [citra-emu/citra-web#43]
After being here a few months, I noticed that the workflow for articles is messy at best. So, instead of the usual digging in the issue tracker, and chasing developers for interviews, I thought it would be best to have a period near the end of the month, where developers can just comment on an issue what pull requests they feel would be great to include in that month's progress report.

For this month, I'll leave the RFC open until 2017-08-28 12:00 UTC-4, give or take a few hours. After that, I'll sift through and find the shiniest pearls, interview and write the article in the week or two after that, and open a pull request for final reviewing for one more week.

Having set schedules will also help add a sense of responsibility for writing this article, so I hope we can be a bit more consistent about writing in the future.

**Comment by anodium** [comment]
Let's start off with the PRs that were supposed to be in last month's report, just so we don't forget:

 - [GPU: Fix Edge Cases for TextureCopy](https://github.com/citra-emu/citra/pull/2809) by [wwylele](https://github.com/wwylele)
 - [Citra-QT: UI Themes](https://github.com/citra-emu/citra/pull/2804) by [Kloen](https://github.com/kloen)
 - [Load Shared Font From System Archive](https://github.com/citra-emu/citra/pull/2784) by [wwylele](https://github.com/wwylele)

and the suggested PRs in the report's review itself:

 - [Add address conversion functions returning optional, Add function to flush virtual region from rasterizer cache](https://github.com/citra-emu/citra/pull/2799) by [yuriks](https://github.com/yuriks)
 - [pica/shader_interpreter: fix off-by-one in LOOP](https://github.com/citra-emu/citra/pull/2848) by [wwylele](https://github.com/wwylele)
 - [gl_rasterizer_cache: fix using_depth_fb](https://github.com/citra-emu/citra/pull/2834) by [wwylele](https://github.com/wwylele)
 - [gl_rasterizer: use texture buffer for proctex LUT](https://github.com/citra-emu/citra/pull/2816) by [wwylele](https://github.com/wwylele)

Despite these PRs being from July, I ask that you please only suggest PRs that were *merged* after 1 August. Which also implies, of course, that you only suggest PRs that were *actually* merged. 😅

**Comment by wwylele** [comment]
> gl_rasterizer: use texture buffer for proctex LUT by wwylele

this is basically a no-op and hard to explain to general user...

**Comment by j-selby** [comment]
Software renderer has been getting a whole bunch of fixes - https://github.com/citra-emu/citra/pull/2871 from wwylele - spot light
Could talk about https://github.com/citra-emu/citra/pull/2869 from me - working Linux nightly builds.
and citrahax if you are really desperate for content - https://github.com/citra-emu/citra/pull/2850

**Comment by anodium** [comment]
* The other parts of swrast that @j-selby mentioned:
    * [Implement fragment lighting in the sw renderer (take 2)](https://github.com/citra-emu/citra/pull/2822)
    * [SwRasterizer/Lighting: implement geometric factor](https://github.com/citra-emu/citra/pull/2872)
    * [SwRasterizer/Lighting: implement bump mapping](https://github.com/citra-emu/citra/pull/2891)
 * [Refactor MotionEmu into a InputDevice](https://github.com/citra-emu/citra/pull/2861) by [wwylele](https://github.com/wwylele)

**Comment by wwylele** [comment]
FYI the SwRasterizer progress in this month all have their hw renderer counterpart in the previous progress reports. You can mention this in the report
#1264 ([2015P2](https://citra-emu.org/entry/citra-progress-report-2015-p2/))-> #2766/#2822 (remember to credit this to Subv)
#2727 -> #2871
#2762 -> #2891
#2776 -> #2872

**Comment by anodium** [comment]
RFC is now closed. I'll now start researching the PRs listed *above* this comment, but the issue won't be closed until the report is merged into [citra-emu/citra-web@master](https://github.com/citra-emu/citra-web/tree/master).

**Comment by anodium** [comment]
Fixed in #48
