### ISSUE TITLE
Broken formatting in wiki pages

### ISSUE THREAD

**Issue by JayFoxRox** [citra-emu/citra-web#5]
This is a temporary meta thread for formatting issues in the wiki pages of our website.

We should focus on getting better github markdown support in hugo (?) instead of fixing these individually unless there's an actual bug in our wikis.

---

## https://citra-emu.org/wiki/User-Directory/ (Report by Leo121)

I changed to square brackets and it didn't fix it:

![](http://i.imgur.com/B23rFyJ.png)
![](http://i.imgur.com/AYncBE2.png)

## https://citra-emu.org/wiki/User-Directory/ (Report by Leo121)

Also an issue with "

![](http://i.imgur.com/otTxuvE.png)
![](http://i.imgur.com/Ef9r0Zm.png)

## https://citra-emu.org/wiki/FAQ/ (Report by Flamboyant Ham)

The website displays links incorrectly.
![](http://i.imgur.com/A7ZyKbs.png)
![](http://i.imgur.com/MvuvMVU.png)

**Comment by chris062689** [comment]
The issues with HTML encoding are probably caused by 
https://github.com/citra-emu/citra-web/blob/master/scripts/wiki/app.js#L44

The issues with converting Github internal links to markdown links, is probably caused by
https://github.com/citra-emu/citra-web/blob/master/scripts/wiki/app.js#L44
or
https://github.com/citra-emu/citra-web/blob/master/scripts/wiki/app.js#L44

**Comment by Schplee** [comment]
> https://citra-emu.org/wiki/FAQ/

Temporary solution to the issue was separate the two links into separate lines. 

The issue is that the site isn't correctly interpreting the markdown on github, so the link would look like "...\[Dumping Game Cartridges]]-and-[Dumping Installed Titles" rather than two separate articles links.

**Comment by JayFoxRox** [comment]
Workaround =/= resolved.

If you have a case to replicate this, create an issue about it so someone can fix it.

**Comment by Schplee** [comment]
Issues resolved/no longer relevant
