### ISSUE TITLE
[RFC] Progress Report 2017 September

### ISSUE THREAD

**Issue by anodium** [citra-emu/citra-web#53]
Back on the chopping block once more. This time the RFC will be running from 2017-09-19 14:30 UTC-4, to 2017-09-26 15:00 UTC-4. But PRs will be accepted until 2017-10-01 00:00 UTC-4, though they'll be lower priority.

Again, make sure the PRs were merged after 2017-09-01, and make sure they were actually *merged*. 😛

**Comment by Subv** [comment]
https://github.com/citra-emu/citra/pulls?utf8=%E2%9C%93&q=is%3Apr%20is%3Amerged%20merged%3A%3E%3D2017-09-01

#2842 Unique page table to each process (slowdown with the JIT)
#2858 Perform interpolation of audio buffers on a frame-by-frame basis.
#2865 Geometry shaders
#2900 PICA: implement custom clip plane
#2915 load different shared font depending on the region 
#2933 Improved performance of FromAttributeBuffer

**Comment by Subv** [comment]
#2952 Switchable page tables in Dynarmic - restores the speed of the JIT to what it was before #2842
#2951 Optimized MortonInterleave - provides a small speed boost
#2933 Slightly improved FromAttributeBuffer on some compilers
#2927 Support for loading application updates
#2921 Fixes GPU batching errors

**Comment by anodium** [comment]
Surprisingly I managed to get here on time, despite hurricane Maria destroying most of the infrastructure.

Anyways, good to know there's a ton of changes this month, this is going to be fun. 😄

Because of the lack of infrastructure, I'm probably going to contact the authors through email or IRC this time, rather than Discord, as both consume significantly less power and bandwidth.

**Comment by Subv** [comment]
One last PR in for the ride!

#2958 Audio: Use std::deque instead of std::vector for the audio buffer type (StereoBuffer16)
