### ISSUE TITLE
Documentation is lacking

### ISSUE THREAD

**Issue by JayFoxRox** [citra-emu/citra-web#6]
README.md should be improved.
Please use this discussion until we have a PR to propose more things which should be documented.

---

This was mentioned by @chris062689 on private discord:

> To run the website locally, fork (or clone) https://github.com/citra-emu/citra-web, download the Hugo binary at https://gohugo.io, drop the Hugo binary in the site folder, and run `hugo serve`

---

I also think we should document how and where the website is hosted, who is in charge of passwords etc. We should keep such information up to date (in the README) and set up a policy so that we never have a single point of failure (consider timezones and regions in this).
(So if tragedy strikes or whatever, we'll still be able to recover the website or have someone knowledgeable)

**Comment by chris062689** [comment]
@bunnei has all of the documentation, accounts, and passwords for the infrastructure. 
The documentation is a bit out of date since we moved to Linode, which will require updating. 

I believe the internal Citra documentation is, and should be, separate from documentation on citra-web.

**Comment by TheKoopaKingdom** [comment]
Closing this because [d991265166531da3917aa8d8f91692a6d24e4a45](https://github.com/citra-emu/citra-web/commit/d991265166531da3917aa8d8f91692a6d24e4a45) and [46434df5e8ff83fca0b5b2c65f65b5a588fe2000](https://github.com/citra-emu/citra-web/commit/46434df5e8ff83fca0b5b2c65f65b5a588fe2000) add documentation.
