### ISSUE TITLE
Progress Report 2017 October

### ISSUE THREAD

**Issue by anodium** [citra-emu/citra-web#65]
Double the progress report, double the ~~torture~~ FUN!

RFC will be open from 2017-11-25 08:00-0400 to 2017-12-10 23:59-0400.
Only PRs that were *merged* between 2017-10-01 and 2017-10-31.

**Comment by j-selby** [comment]
https://github.com/citra-emu/citra/pulls?utf8=%E2%9C%93&q=is%3Apr+merged%3A2017-10-01..2017-10-31

https://github.com/citra-emu/citra/pull/2966: Installer
https://github.com/citra-emu/citra/pull/3001: Fullscreen

**Comment by shinyquagsire23** [comment]
citra-emu/citra#2993: AM is able to scan for titles on SDMC and NAND and list them to processes. Content accesses for titles are directed to the appropriate .app files (for DLC and game manuals), ExeFS file accesses are implemented. Home menu and MSET are now able to display installed titles.
citra-emu/citra#3048: Implemented another AM function, fixes Flipnote Studio

**Comment by Subv** [comment]
https://github.com/citra-emu/citra/pull/2975 Allows loading real NCCH files as they are in the 3DS's filesystem instead of the butchered version we required before. It also allows overriding NCCH sections like .code without having to rebuild the entire NCCH
