### ISSUE TITLE
Progress Report 2017 November

### ISSUE THREAD

**Issue by anodium** [citra-emu/citra-web#66]
Double the progress report, double the ~~torture~~ FUN!

RFC will be open from 2017-11-25 08:00-0400 to 2017-12-10 23:59-0400.
Only PRs that were *merged* between 2017-11-01 and 2017-11-30.

**Comment by j-selby** [comment]
#3081: About box (might want to slip this in ala Dolphin at the end as the most important feature)
#3113: Initial CIA support

**Comment by MerryMage** [comment]
citra-emu/citra#2982: if you want to mention super lazy macOS-only performance improvement (just flipping compiler switches to enable AVX2 on supported systems)

**Comment by B3n30** [comment]
I would love to have a chapter about how @wwylele investigated the appveyor issue: https://github.com/citra-emu/citra/issues/3051. How we had the fix but knew it will fail in the future...
And then he finally found the issue and there is the solution: https://github.com/citra-emu/citra/pull/3141

**Comment by shinyquagsire23** [comment]
citra-emu/citra#3029: Implementation for title installs within AM service, ie for installing CIAs from FBI, possibly Download Play in the future (would need crypto support)
citra-emu/citra#3113: SDL backend for CIA installation, CIAs can be installed with `citra -i <cia path>` instead of having to use FBI.

**Comment by YOUDONTSAYMEMEWILLBEMINE** [comment]
https://github.com/citra-emu/citra/pull/3116 Gamepad support

**Comment by anodium** [comment]
@YOUDONTSAYMEMEWILLBEMINE citra-emu/citra#3116 still hasn't been merged, and since it's already 2017-12-01 00:55-0400, it is impossible that it will ever be merged in 2017 November.

I appreciate the enthusiasm but I can only report on PRs that were actually merged into [citra-emu/citra@master](https://github.com/citra-emu/citra/tree/master) *during* November. 😅

Also, this PR seems to add a Qt UI for configuring inputs, not gamepad support. Gamepad support per sé was added back in citra-emu/citra#2497.

**Comment by Subv** [comment]
https://github.com/citra-emu/citra/pull/3119 Porting Dolphin's CoreTiming to fix some event latency issues we had.
Maybe we could talk a bit about the possibility of doing system-module LLE (#2981, #3082, #3083, #3084 and #3088)

**Comment by TheKoopaKingdom** [comment]
Since it seems only the SDL frontend has been mentioned: citra-emu/citra#3144 (QT CIA installation.).

**Comment by Subv** [comment]
@TheKoopaKingdom That was merged in December tho
