### ISSUE TITLE
Progress Report 2017 December

### ISSUE THREAD

**Issue by anodium** [citra-emu/citra-web#67]
Unlike #65 and #66, because December is still ongoing, this is a living breathing document, that should have PRs added to it as they are merged.

RFC will be open from 2017-12-11 09:15-0400 to 2018-01-02 09:15-0400.
Again, make sure that the PR has *already* been merged to `master` before adding a comment here.

Wow, can't believe the year's almost over.

**Comment by MerryMage** [comment]
[List of PRs merged in the month of December](https://github.com/citra-emu/citra/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aclosed+merged%3A2017-12-01T00%3A00%3A00%2B00%3A00..2018-01-01T00%3A00%3A00%2B00%3A00).

**Comment by B3n30** [comment]
I think #3091 together with #3184, #3116, #3144. Then we have a lot of LLE support (applets), speed improvements (mainly Merry's dynarmic updates), all the IPC_ServiceFramework stuff, and maybe the beginning of the home_menu support. It's really a lot of PRs for only 1/3rd of December

**Comment by Leo626** [comment]
Some worth mentioning:

citra-emu/citra#3091: Kernel/IPC: Add a small delay after each SyncRequest to prevent thread starvation (Fixed freezing in a lot of games)
citra-emu/citra#3116: Allow input configuration with SDL joysticks
citra-emu/citra#3144: QT CIA installation
