### ISSUE TITLE
Thumbnails on screenshots page are just downsized images (high bandwidth usage)

### ISSUE THREAD

**Issue by JayFoxRox** [citra-emu/citra-web#7]
What the title says.

Ideally we'd store / generate a downsized version of the screenshots to save on bandwidth.

**Comment by chris062689** [comment]
We can store thumbnail versions of the screenshots using the same gulp method we use for banners and jumbotron images.

https://github.com/citra-emu/citra-web/blob/fc0c95af2cf1f07633496964bfd488295e14144c/gulpfile.js#L64

**Comment by chris062689** [comment]
Fixed by creating a thumbs folder with gulp. 
1a41025f95d54ae7d119cd40725c799efe31581a
