### ISSUE TITLE
Progress Report 2018 January

### ISSUE THREAD

**Issue by anodium** [citra-emu/citra-web#71]
Because the month is still ongoing, this is a living breathing document, that should have PRs added to it as they are merged.

RFC will be open from 2018-01-18 08:45-0400 to 2018-02-02 23:59-0400.
Again, make sure that the PR has already been merged to `master` before adding a comment here.

Here's the [list of PRs this month that have been merged](https://github.com/citra-emu/citra/pulls?utf8=%E2%9C%93&q=is%3Apr+closed%3A2018-01-01T00%3A00%3A00%2B00%3A00..2018-02-01T00%3A00%3A00%2B00%3A00).

**Comment by Leo626** [comment]
- citra-emu/citra#3297 citra-qt: add translation support; link translation with transifex 
- citra-emu/citra#3325 Add ability to send test cases through telemetry 
- citra-emu/citra#3402 Allow Installed Apps to Display in the Game List 
- citra-emu/citra#3353 citra-qt: Add customizable speed limit target

**Comment by Hexagon12** [comment]
This has been sitting for a while now. I know the situation behind this.

Requesting to close.

**Comment by anodium** [comment]
Closed by #84
