### ISSUE TITLE
Arrows on carousel show as Ẁ and Z while loading

### ISSUE THREAD

**Issue by JayFoxRox** [citra-emu/citra-web#8]
(This is only a minor issue)

While the page is loading these arrows show as wrong symbols (Chromium 56.0.2924.87).
For me, the page sometimes loads very long (> 2 seconds) so we should probably just avoid this.

This does also happen for me when running the page locally in hugo during development (maybe glyphicon is stored on an "insecure location" / server in that case?)

---

One can reproduce the issue by removing the glyphicon `class` for the arrows.

We could replace them with images /  unicode arrows or just make sure that the font / glyphicon style is loaded before the left/right glyphicon style.

**Comment by chris062689** [comment]
I'll have to scan through the website to see if we use glyphcons elsewhere.

I believe they're also used for the down arrows in the dropdown menu.

**Comment by Eric-Jackson** [comment]
Should honestly be using SVGs anyway. Would be willing to switch these to SVG sprites if it's of any interest @chris062689

**Comment by chris062689** [comment]
I'd be all for replacing the dependency of Bootstrap's glyphicons. Can we put together a PR identifying everywhere glyphicons are being used on the website, and look into phasing those out?

**Comment by chris062689** [comment]
This has been resolved by reworking the development website to use gulp and browsersync.
