### ISSUE TITLE
Progress Report 2018 Q2

### ISSUE THREAD

**Issue by anodium** [citra-emu/citra-web#85]
RFC for the second quarter of 2018. Suggestions for featured pulls will be taken from 2018-07-02 10:00 UTC-5 to 2018-07-09 12:00 UTC-5. PRs must have been **merged** between 2018-05-20 and 2018-07-31, they may be accepted past the RFC due date, but they will be lower priority.

**Comment by MerryMage** [comment]
[Merged PRs within this date range](https://github.com/citra-emu/citra/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Amerged+closed%3A2018-07-01T00%3A00%3A00%2B00%3A00..2018-08-01T00%3A00%3A00%2B00%3A00+).

**Comment by MerryMage** [comment]
UI: 

* [citra_qt: Add Continue/Pause & Toggle Speed Limit hotkeys - valentinvanelslande](https://github.com/citra-emu/citra/pull/3594)
* [QT: Add support for multiple game directories -  BreadFish64](https://github.com/citra-emu/citra/pull/3617)

Extra Features:

* [Add Support for Stereoscopic 3D - N00byKing](https://github.com/citra-emu/citra/pull/3632)

Graphics (wwylele MVP)

* 
*  shadow map 2D/Cube - https://github.com/citra-emu/citra/pull/3778
* Shader JIT improvements: https://github.com/citra-emu/citra/pull/3787, https://github.com/citra-emu/citra/pull/3788
* degasus's PRs - https://github.com/citra-emu/citra/pull/3724, https://github.com/citra-emu/citra/pull/3789

Audio

* Cubeb backend - https://github.com/citra-emu/citra/pull/3776
